global using Reservation.Application.ReserveTimes.Commands.CreateReserveTime;
global using Reservation.Application.ReserveTimes.Exceptions;
global using Reservation.Application.Businesses.Exceptions;
global using Reservation.Domain.Entities.Businesses;
global using Reservation.Domain.UnitOfWork;
global using NSubstitute;
global using Shouldly;
global using MediatR;
global using Xunit;
