global using Microsoft.Extensions.DependencyInjection;
global using Reservation.Share.Abstract.Exceptions;
global using System.Text.RegularExpressions;
global using System.Security.Cryptography;
global using Microsoft.AspNetCore.Builder;
global using Reservation.Share.Exceptions;
global using Microsoft.AspNetCore.Http;
global using System.Text.Json;
global using System.Text;